#pragma once
#include <vector>
#include "BubbleSort.h"
#include "SelectionSort.h"
#include "InsertionSort.h"
#include "MergeSort.h"
#include "ShellSort.h"
#include "HeapSort.h"
#include "QuickSort.h"
#include "RadixSort10.h"
#include "RadixSort16.h"
#include "RadixSortMasking.h"