#include <iostream>
#include <fstream>
#include <random>
#include <ctime>
#include <string>
#include <random>
enum MenuType { MAKENEW = 1, EXIT };
enum DataType { INT = 11, DOUBLE, STRING, RECTANGLE };

//const std::string PATH = "C:\\Users\\Administrator\\source\\repos\\dldhk97\\MyDevelopment\\C++\\RandomDataCreator\\Debug\\";		//절대 경로 사용 시
const std::string PATH = "";																										//기본 경로 사용 시

int getIntRandomNumber(int min, int max)
{
	//< 1단계. 시드 설정
	std::random_device rn;
	std::mt19937_64 rnd(rn());

	//< 2단계. 분포 설정 ( 정수 )
	std::uniform_int_distribution<int> range(min, max);	

	//< 3단계. 값 추출
	return range(rnd);
}

int getDoubleRandomNumber(double min, double max)
{
	//< 1단계. 시드 설정
	std::random_device rn;
	std::mt19937_64 rnd(rn());

	//< 2단계. 분포 설정 ( 실수 )
	std::uniform_real_distribution<double> range(min, max);

	//< 3단계. 값 추출
	return range(rnd);
}

int getMenu()
{
	int userInput;
	std::cout << "==========" << "\n";
	std::cout << "1. 생성" << "\n";
	std::cout << "2. EXIT" << "\n";
	std::cout << "==========" << "\n";
	std::cin >> userInput;
	if (MAKENEW <= userInput && userInput <= EXIT)
		return userInput;
	std::cout << "입력 오류" << "\n";
}

void writeInt(std::string fileName, int cnt)
{
	std::ofstream os(fileName);

	srand((unsigned int)time(NULL));
	for (int i = 0; i < cnt; i++)
	{
		os << getIntRandomNumber(1 ,INT_MAX) << "\n";
	}

	std::cout << "INT 완료" << "\n";
}

void writeDouble(std::string fileName, int cnt)
{
	std::ofstream os(fileName);
	std::random_device rd;  //Will be used to obtain a seed for the random number engine
	std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
	std::uniform_real_distribution<> dis(0.0, 1.0);
	for (int n = 0; n < cnt; ++n) {
		// Use dis to transform the random unsigned int generated by gen into a 
		// double in [1, 2). Each call to dis(gen) generates a new random double
		os << dis(gen) << "\n";
	}
	

	std::cout << "DOUBLE 완료" << "\n";
}

void genRandStr(char* s, const int len)
{
	static const char alphanum[] =
		"0123456789"
		"ABCDEFGHIJKLMNOPQRSTUVWXYZ"
		"abcdefghijklmnopqrstuvwxyz";

	for (int i = 0; i < len; ++i)
	{
		s[i] = alphanum[rand() % (sizeof(alphanum) - 1)];
	}

	s[len] = 0;
}

void writeString(std::string fileName, int cnt)
{
	std::ofstream os(fileName);

	srand((unsigned int)time(NULL));
	for (int i = 0; i < cnt; i++)
	{
		char s[9];
		int length = rand() % 8 + 1;			//문자열의 길이도 난수로 하고 싶으면 rand() % 100으로 대체할 것.
		genRandStr(s, length);

		os << std::string(s) << "\n";
	}
	std::cout << "STRING 완료" << "\n";
}

void writeRectangle(std::string fileName, int cnt)
{
	std::ofstream os(fileName);

	srand((unsigned int)time(NULL));
	for (int i = 0; i < cnt; i++)
	{
		os << rand() % 100 + 1 << " " << rand() % 100 + 1 << "\n";
	}

	std::cout << "RECTANGLE 완료" << "\n";
}


void makeNewFile()
{
	std::string fileName;
	int cnt;
	std::cout << "개수 입력 :";
	std::cin >> cnt;
	fileName = std::to_string(cnt);

	writeInt(PATH + "int - " + fileName + ".txt", cnt);
	writeDouble(PATH + "double - " + fileName + ".txt", cnt);
	writeString(PATH + "string - " + fileName + ".txt", cnt);
	writeRectangle(PATH + "rectangle - " + fileName + ".txt", cnt);
}

int main()
{
	int userInput;

	while (1)
	{
		userInput = getMenu();
		if (userInput == EXIT)
			break;
		switch (userInput)
		{
		case MAKENEW:
			makeNewFile();
			break;
		default:
			std::cout << "ERROR";
			break;
		}
	}
	return 0;
}